type = "directrequest"
schemaVersion = 1
name = "change-tokens"
maxTaskDuration = "0s"
contractAddress = "0xf7e113AF5C0e7D19002EEEbCdae11a2Da66Af00B" # operator contract mumbai
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type=cborparse data="$(decode_log.data)"]

    decode_log -> decode_cbor -> fetch
    fetch        [type="http" method=GET url="https://cyclimate-backend-node.herokuapp.com/burned"]

    cid          [type=jsonparse path="data,cid"]
    ret_url      [type=jsonparse path="data,ret_url"]
    claim        [type=jsonparse path="data,claim"]

    fetch -> ret_url
    fetch -> cid 
    fetch -> claim 

    ret_url -> encode_data
    cid -> encode_data
    claim -> encode_data

    encode_data  [type=ethabiencode abi="(bytes32 requestId,address to, string cid, string ret_url, uint256 claim )" data="{\\"requestId\\": $(decode_log.requestId),\\"to\\": $(decode_cbor.to),\\"cid\\": $(cid),\\"ret_url\\": $(ret_url),\\"claim\\": $(claim) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"]
    submit_tx    [type=ethtx to="0xf7e113AF5C0e7D19002EEEbCdae11a2Da66Af00B" data="$(encode_tx)" gasLimit="2500000"]
    encode_data -> encode_tx -> submit_tx
"""
